### ISSUE TITLE
Documentation on Training & predicting

### ISSUE THREAD

**Issue by ghost** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#1]
@lvoegtlin @Renthal @vinaychandranp 

Can you share documentation on how to Train & Predict?

**Comment by Renthal** [comment]
Currently there is no official external documentation. The code is documented according to Numpy notation standard. 

There is no training required for the algorithm and the entry point for running it is  `src/line_segmentation/line_segmentation.py`. Towards the bottom of the file there is an example of how to run it. Please let us know if you have specific questions.

**Comment by ghost** [comment]
@Renthal I copied `line_segmentation.py` to the main directory, and changed the `input_path` to `test2.png` and ran it, I got error:
```
(tls) home@home-desktop:~/programs/tle$ python line_segmentation.py 
Traceback (most recent call last):
  File "line_segmentation.py", line 130, in <module>
    vertical=False)
  File "line_segmentation.py", line 47, in extract_textline
    img = prepare_image(img, testing=testing, cropping=False, vertical=vertical)
  File "/home/home/programs/tle/src/line_segmentation/preprocessing/load_image.py", line 52, in prepare_image
    assert len(np.unique(img[:, :, 1])) == 1
AssertionError
```

**Comment by Renthal** [comment]
The assertion is verifying that the input image has only a single value on the green channel (typically 0).
You can see how the input image should be formatted here: https://github.com/DIVA-DIA/DIVA_Layout_Analysis_Evaluator/blob/master/README.md at the GT format part.

___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>
.
...:

On 6 Aug 2019, at 19:29, deepseek <notifications@github.com<mailto:notifications@github.com>> wrote:


@Renthal<https://github.com/Renthal> I copied line_segmentation.py to the main directory, and changed the input_path to test2.png and ran it, I got error:

(tls) home@home-desktop:~/programs/tle$ python line_segmentation.py
Traceback (most recent call last):
  File "line_segmentation.py", line 130, in <module>
    vertical=False)
  File "line_segmentation.py", line 47, in extract_textline
    img = prepare_image(img, testing=testing, cropping=False, vertical=vertical)
  File "/home/home/programs/tle/src/line_segmentation/preprocessing/load_image.py", line 52, in prepare_image
    assert len(np.unique(img[:, :, 1])) == 1
AssertionError

**Comment by ghost** [comment]
@Renthal I have tested on this image [test image.zip](https://github.com/DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts/files/3490256/test.image.zip)

I even tested on different channels using:
```
convert test9.png  -channel RGB  -separate  channels_%d.png
```

All getting the same AssertionError
I want to test your code,  can you look into it?
