### ISSUE TITLE
Cannot create conda environment (libtiff resolve error)

### ISSUE THREAD

**Issue by stevethearkiv** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#2]
Hello. Have cloned latest version of repo and installed latest version of anaconda.

Creating env results in following error..

conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libtiff==4.0.10=h648cc4a_1001

OS: Ubuntu 18.04.4 LTS

dpkg -l | grep libtiff 

ii  libtiff-dev                                       4.0.9-5ubuntu0.3                                 amd64        Tag Image File Format library (TIFF), development files, current version
ii  libtiff5:amd64                                    4.0.9-5ubuntu0.3                                 amd64        Tag Image File Format (TIFF) library
ii  libtiff5-dev:amd64                                4.0.9-5ubuntu0.3                                 amd64        Tag Image File Format library (TIFF), development files
ii  libtiffxx5:amd64                                  4.0.9-5ubuntu0.3                                 amd64        Tag Image File Format (TIFF) library -- C++ interface

**Comment by lvoegtlin** [comment]
Hei, thanks for the issue.

I updated the environment file. Could you try again with the new version? If there are still problems just drop again a comment and we try to fix it.

**Comment by stevethearkiv** [comment]
Hi. I havent tried the new environment file, but I managed to find a fix late last night before you answered, which was just to leave libtiff with no specified version

**Comment by stevethearkiv** [comment]
I will check out the new and see if it builds without problem
