### ISSUE TITLE
input directory and output [suggestion]

### ISSUE THREAD

**Issue by ghost** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#3]
it would be great having the option to select input and output directory. 
segmenting all the images in a directory

**Comment by lvoegtlin** [comment]
You can just call the evaluate() in the file evaluate_algorithm.py. It takes a folder of input files and input gt. 
I hope this "solves" the problem. I agree that we could put it into a more prominent place
