### ISSUE TITLE
ModuleNotFoundError when running line_segmentation.py

### ISSUE THREAD

**Issue by stevethearkiv** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#4]
When running python ./src/line_segmentation/line_segmentation.py, I had to add

import sys
sys.path.append('./')

to the file ./src/line_segmentation/line_segmentation.py

Otherwise following errors were produced

python ./src/line_segmentation/line_segmentation.py
Traceback (most recent call last):
  File "./src/line_segmentation/line_segmentation.py", line 6, in <module>
    import src.line_segmentation.preprocessing.energy_map
ModuleNotFoundError: No module named 'src'

**Comment by lvoegtlin** [comment]
I extended the readme which should "solve" this problem. 
Everything is programmed in a way that you have to start from the project's root folder (e.g. python ./src/...) else you run into path and import problems

**Comment by stevethearkiv** [comment]
I was executing from the root. It should have found them, but did not unless I added ./ to sys.path

**Comment by lvoegtlin** [comment]
Or you could have added . to the PYTHONPATH (export PYTHONPATH=$PYTHONPATH:.)
