### ISSUE TITLE
Assertion when running line_segmentation.py against png file

### ISSUE THREAD

**Issue by stevethearkiv** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#5]
Hello. I ran line_segmentation with following settings

extract_textline(input_path='./src/data/test.png',
                     output_path='./output',
                     seam_every_x_pxl=100,
                     penalty_reduction=6000,
                     testing=False,
                     console_log=True,
                     vertical=False)

Follow error was produced.

python ./src/line_segmentation/line_segmentation.py
Traceback (most recent call last):
  File "./src/line_segmentation/line_segmentation.py", line 133, in <module>
    vertical=False)
  File "./src/line_segmentation/line_segmentation.py", line 50, in extract_textline
    img = prepare_image(img, testing=testing, cropping=False, vertical=vertical)
  File "./src/line_segmentation/preprocessing/load_image.py", line 52, in prepare_image
    assert len(np.unique(img[:, :, 1])) == 1
AssertionError

Image attached in next comment, but the error also occurs with all the test png files included in the repo

**Comment by stevethearkiv** [comment]
![test](https://user-images.githubusercontent.com/15155102/86216008-a7dff580-bb7d-11ea-88d5-72e4b0495547.png)

**Comment by lvoegtlin** [comment]
Please check again the readme (i just updated it). It should answer all your questions

**Comment by stevethearkiv** [comment]
I am not sure it does. What kind of segmentation do you mean? Page segmentation? I.e change this from a double to a single page?

**Comment by stevethearkiv** [comment]
The assertion occurs also on the test*.png files included in src/data which came with the source code, so I dont think that lack of page segmentation is the problem here?

**Comment by lvoegtlin** [comment]
> I am not sure it does. What kind of segmentation do you mean? Page segmentation? I.e change this from a double to a single page?

pixel-vise semantic segmentation s.t. every pixel has a class label (as describes in the readme and the paper). 
Also, we did not investigate our performance on double pages, hence, we can not guarantee a successful segmentation.

When you use a test image you need to have the parameter *--testing* on True as the testing image has a special encoding.

I would recommend to pull again the code, as I added a CLI for the single file segmentation (line_segmentation.py) which should work out of the box.
