### ISSUE TITLE
How do I save segmented lines images

### ISSUE THREAD

**Issue by vanlar-cyber** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#6]
Hello sir, I run you codes and every code works fine. How do I crop the segmented lines images? Because it only saves images with red seams.
What are stored in "lines" list?

**Comment by lvoegtlin** [comment]
Hei
The system does not provide automatic cropping. You would need to create a script that iterates over the segmented lines in the file `polygons.xml` and cuts the lines out of the image.
What do you mean by "lines list"?

**Comment by vanlar-cyber** [comment]
Thanks so much for your reply.
In line_segmentation.py file, there you call majority_voting method and put
its returned values to
lines, centroids, values.
What values are stored in lines?
When I show the values in it, it shows some arrays inside a list and
len(lines) is 5. I don't get what "lines" here means.

**Comment by lvoegtlin** [comment]
This variable saves the coordinates of the lines. So if you find 5 lines the `lines` variable has length 5 and each of these lines is then defined with n amount of points. E.g. lines = [[1,2,3],[4,5,6],[7,8,9]] where lines[0] describes the coordinates of the first line.

**Comment by vanlar-cyber** [comment]
Then how can I cut the lines using "lines" variable?

**Comment by lvoegtlin** [comment]
You have two options:
- create a script that takes the original image and the polygon.xml file. Then cut out the polygon on the original image
- inject your code in the line_segmentation.py and cut out the polygons directly there 

So you have a polygon for each line found based on which you can use a library like pillow to cut this line out of the original image

**Comment by vanlar-cyber** [comment]
Yes sir, thank you.
I tried to directly cut the lines from polygons. But the result really
confused me.
Here is my code for cropping polygons.
*def cut_polygons(img, polygons):*
*    for i in range(len(polygons)):*

*        pts = polygons[i].astype(np.int <http://np.int>)*

*        ## (1) Crop the bounding rect*
*        (x, y, w, h) = cv2.boundingRect(pts)*

*        line = img[y:y+h, x:x+h].copy()*

*        ## (2) make mask    *
*        pts = pts - pts.min(axis=0)*

*        mask = np.zeros(line.shape[:2], np.uint8)*
*        cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1,
cv2.LINE_AA)*

*        ## (3) do bit-op*
*        dst = cv2.bitwise_and(line, line, mask=mask)*

*        ## (4) add the white background*
*        bg = np.ones_like(line, np.uint8)*255*
*        cv2.bitwise_not(bg,bg, mask=mask)*
*        dst2 = bg + dst*

*        cv2.imwrite("line"+str(i)+".png", line)*
*        cv2.imwrite("mask"+str(i)+".png", mask)*
*        cv2.imwrite("dst"+str(i)+".png", dst)*
*        cv2.imwrite("dst2"+str(i)+".png", dst2)*


Here are some of  the results I got for the cropped lines testing the
image(test1.png) on your repo.

Please, help me sir. I appreciate.

**Comment by lvoegtlin** [comment]
I can not see the attachment you are putting into the response email you have to use the issue function on Github.

As I never used OpenCV for image manipulation I can not help you with that (care: OpenCV uses another coordinate system!). 

I would use this technique (https://stackoverflow.com/questions/22588074/polygon-crop-clip-using-python-pil) and combine it with this script [here](https://github.com/lvoegtlin/page_onto_image). You can just remove the drawing with the cutting and you should be good to go.
