### ISSUE TITLE
Ground truth format

### ISSUE THREAD

**Issue by vanlar-cyber** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#7]
To run own images, I need to do input ground truth formatted images. Then, which program do I need to run to make new images into ground truth formats? I have read Readme but I am still confused with it. Thank you.

**Comment by lvoegtlin** [comment]
Hei,
There are no programs that transform certain ground truth into the DIVAHisDB format. You need to write your own tool. The description of the format you find [here](https://github.com/DIVA-DIA/DIVA_Layout_Analysis_Evaluator#ground-truth-format) and the paper which describes the dataset (DIVAHisDB) and its format [here](https://ieeexplore.ieee.org/abstract/document/7814109)

**Comment by vanlar-cyber** [comment]
@lvoegtlin thank you. Is there any pretrained model to do this pixel wise semantic segmentation?

**Comment by lvoegtlin** [comment]
At the moment not but we are working in the next months on some baseline models which we could share later on.
