### ISSUE TITLE
Asking results in the papers

### ISSUE THREAD

**Issue by Nam-pfiev1995** [DIVA-DIA/Text-Line-Segmentation-Method-for-Medieval-Manuscripts#8]
Dear authors,
Thanks for sharing great code. 

I am writing a paper and reference to your paper. So, I would like to know results in your paper [https://arxiv.org/abs/1906.11894](url) are evaluated on the private test or public test or both.

Thanks in advance.
Nam

**Comment by lvoegtlin** [comment]
Hei @Nam-pfiev1995 
We evaluated our method on the private testset as this is the set that was used to test for the competition.

Cheers

**Comment by Nam-pfiev1995** [comment]
I got it, Thank you so much.

Nam
